# Generated by Django 5.1.9 on 2026-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RMPMComponentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(db_index=True, help_text="Unique component identifier (must not start with '7')", max_length=100, unique=True)),
                ('component_description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('RM', 'Raw Material'), ('PM', 'Packaging Material')], db_index=True, default='RM', max_length=10)),
                ('uom', models.CharField(default='PC', max_length=20)),
                ('default_storage_location', models.CharField(blank=True, default='', max_length=50)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_common_part', models.BooleanField(db_index=True, default=False)),
                ('shared_in_fgs_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RM/PM Component Master',
                'verbose_name_plural': 'RM/PM Component Master',
                'db_table': 'rm_pm_component_master',
                'ordering': ['component_code'],
                'indexes': [models.Index(fields=['category'], name='rm_pm_compo_categor_1ca001_idx'), models.Index(fields=['is_common_part'], name='rm_pm_compo_is_comm_ba7f08_idx'), models.Index(fields=['is_active'], name='rm_pm_compo_is_acti_39bb9b_idx')],
            },
        ),
    ]
