# Generated by Django 5.1.9 on 2026-09-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMFGHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_code', models.CharField(db_index=True, help_text="Finished good identifier (must start with '7')", max_length=100, unique=True)),
                ('fg_description', models.CharField(max_length=255)),
                ('mini_factory', models.CharField(blank=True, default='', max_length=100)),
                ('line', models.CharField(blank=True, default='', max_length=100)),
                ('customer_segment', models.CharField(blank=True, default='', max_length=100)),
                ('unit_price_inr', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('active_bom_version', models.CharField(default='v1', max_length=20)),
                ('uom', models.CharField(default='PC', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BOM Finished Good Header',
                'verbose_name_plural': 'BOM Finished Good Headers',
                'db_table': 'bom_fg_header',
                'ordering': ['fg_code'],
                'indexes': [models.Index(fields=['mini_factory'], name='bom_fg_head_mini_fa_a774f5_idx'), models.Index(fields=['line'], name='bom_fg_head_line_75ff73_idx'), models.Index(fields=['is_active'], name='bom_fg_head_is_acti_f1a5a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BOMMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('uom', models.CharField(default='PC', max_length=20)),
                ('component_role', models.CharField(blank=True, default='', max_length=50)),
                ('bom_version', models.CharField(default='v1', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('lead_time_days_override', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(db_column='component_code', on_delete=django.db.models.deletion.CASCADE, related_name='bom_usages', to='core.rmpmcomponentmaster', to_field='component_code')),
                ('fg', models.ForeignKey(db_column='fg_code', on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='core.bomfgheader', to_field='fg_code')),
            ],
            options={
                'verbose_name': 'BOM Master',
                'verbose_name_plural': 'BOM Master Lines',
                'db_table': 'bom_master',
                'ordering': ['fg', 'component'],
                'indexes': [models.Index(fields=['fg', 'bom_version', 'is_active'], name='bom_master_fg_code_c01738_idx'), models.Index(fields=['component'], name='bom_master_compone_70ad5b_idx'), models.Index(fields=['is_active'], name='bom_master_is_acti_11a4eb_idx'), models.Index(fields=['bom_version'], name='bom_master_bom_ver_3c417d_idx')],
                'constraints': [models.UniqueConstraint(fields=('fg', 'component', 'bom_version'), name='unique_bom_entry_per_version')],
            },
        ),
    ]
