# Generated by Django 5.1.9 on 2026-09-23 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bomfgheader_bommaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('BOM_UPLOAD', 'BOM Upload'), ('MONTHLY_PLAN', 'Monthly Plan'), ('MB51_REPORT', 'MB51 Report'), ('STOCK_REPORT', 'Stock Report'), ('VENDOR_DELIVERY_SCHEDULE', 'Vendor Delivery Schedule'), ('OTHER', 'Other Upload')], max_length=50)),
                ('uploaded_by', models.CharField(blank=True, default='system', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_name', models.CharField(max_length=255)),
                ('minio_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('error_detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'db_table': 'upload_batch',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['upload_type', 'status'], name='upload_batc_upload__0ff976_idx'), models.Index(fields=['-uploaded_at'], name='upload_batc_uploade_6cc954_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorBuyerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('vendor_name', models.CharField(db_index=True, max_length=255)),
                ('buyer_name', models.CharField(db_index=True, max_length=255)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(choices=[('RM', 'Raw Material'), ('PM', 'Packaging Material')], db_index=True, default='RM', max_length=10)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('gst_no', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Buyer Master',
                'verbose_name_plural': 'Vendor Buyer Master',
                'db_table': 'vendor_buyer_master',
                'ordering': ['vendor_code'],
                'indexes': [models.Index(fields=['vendor_name'], name='vendor_buye_vendor__a2066c_idx'), models.Index(fields=['buyer_name'], name='vendor_buye_buyer_n_b15012_idx'), models.Index(fields=['category'], name='vendor_buye_categor_da59c7_idx'), models.Index(fields=['is_active'], name='vendor_buye_is_acti_c0fee8_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorSuppliedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(db_column='component_code', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_suppliers', to='core.rmpmcomponentmaster', to_field='component_code')),
                ('vendor_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_components_rel', to='core.vendorbuyermaster')),
            ],
            options={
                'verbose_name': 'Vendor Supplied Component',
                'verbose_name_plural': 'Vendor Supplied Components',
                'db_table': 'vendor_supplied_components',
                'ordering': ['vendor_buyer', 'component'],
                'indexes': [models.Index(fields=['vendor_buyer'], name='vendor_supp_vendor__14b180_idx'), models.Index(fields=['component'], name='vendor_supp_compone_ed8cd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor_buyer', 'component'), name='unique_vendor_supplied_component')],
            },
        ),
    ]
