# Generated by Django 5.1.9 on 2026-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadbatch_vendorbuyermaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text="Month bucket in YYYY-MM format, e.g. '2026-08'", max_length=7)),
                ('week_no', models.IntegerField(help_text='Week index within the month (1, 2, 3, 4, 5...)')),
                ('week_code', models.CharField(db_index=True, help_text="Unique week code identifier, e.g. 'w-2026-08-01'", max_length=50, unique=True)),
                ('week_label', models.CharField(help_text="Human-readable label, e.g. 'Week 1 (01-09 Aug)'", max_length=100)),
                ('start_date', models.DateField(help_text='Week bucket starting date (inclusive)')),
                ('end_date', models.DateField(help_text='Week bucket ending date (inclusive)')),
                ('days_count', models.IntegerField(help_text='Total calendar days in this week bucket')),
                ('holiday_days', models.IntegerField(default=0, help_text='Number of holidays / plant off-days')),
                ('working_days', models.IntegerField(help_text='Effective working days available for production')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Week Definition',
                'verbose_name_plural': 'Week Definitions',
                'db_table': 'week_definition',
                'ordering': ['month', 'week_no'],
                'indexes': [models.Index(fields=['month'], name='week_defini_month_0ee0ab_idx'), models.Index(fields=['start_date', 'end_date'], name='week_defini_start_d_ed1e1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('month', 'week_no'), name='unique_week_per_month')],
            },
        ),
    ]
