# Generated by Django 5.1.9 on 2026-09-24 12:22

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_weekdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text="Month bucket in YYYY-MM format, e.g. '2026-08'", max_length=7)),
                ('monthly_target', models.PositiveIntegerField(help_text='Total planned FG production units for the month')),
                ('uom', models.CharField(default='PC', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('custom_notes', models.TextField(blank=True, default='')),
                ('weekly_breakdown', models.JSONField(default=dict, help_text='Computed prorated weekly breakdown JSONB mapping week_code to integer quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fg', models.ForeignKey(db_column='fg_code', help_text='Finished Good header (FK to bom_fg_header)', on_delete=django.db.models.deletion.PROTECT, related_name='monthly_plans', to='core.bomfgheader', to_field='fg_code')),
            ],
            options={
                'verbose_name': 'Monthly Plan',
                'verbose_name_plural': 'Monthly Plans',
                'db_table': 'monthly_plan',
                'ordering': ['month', 'fg__fg_code'],
                'indexes': [models.Index(fields=['month'], name='monthly_pla_month_0950a5_idx'), models.Index(fields=['fg', 'month'], name='monthly_pla_fg_code_4202f3_idx'), django.contrib.postgres.indexes.GinIndex(fields=['weekly_breakdown'], name='idx_monthly_plan_weekly_brk')],
                'constraints': [models.UniqueConstraint(fields=('fg', 'month'), name='unique_monthly_plan_fg_month')],
            },
        ),
    ]
