# Generated by Django 5.1.9 on 2026-09-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monthlyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MB51Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_document', models.CharField(db_index=True, help_text='SAP Material Document number (e.g. 5001089211)', max_length=50)),
                ('posting_date', models.DateField(db_index=True, help_text='Posting date of the material transaction')),
                ('movement_type', models.CharField(help_text='SAP Movement Type e.g. 101, 601', max_length=10)),
                ('part_number', models.CharField(db_index=True, help_text='Material or Component Part Number', max_length=50)),
                ('material_description', models.CharField(blank=True, default='', help_text='Material or Finished Good description', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Transaction quantity', max_digits=12)),
                ('uom', models.CharField(default='PC', max_length=20)),
                ('storage_location', models.CharField(blank=True, default='SL01', help_text='Storage location (e.g. SL01, FG01)', max_length=50)),
                ('plant', models.CharField(blank=True, default='1001', help_text='Plant code', max_length=50)),
                ('vendor_customer', models.CharField(blank=True, default='', help_text='Vendor code/name for 101 receipts or Customer for 601 dispatches', max_length=150)),
                ('po_order_number', models.CharField(blank=True, default='', help_text='Purchase Order or Production Order reference', max_length=100)),
                ('classification', models.CharField(choices=[('FG_PRODUCTION_RECEIPT', 'FG Production Receipt'), ('RMPM_RECEIPT', 'RM/PM Receipt'), ('FG_DISPATCH', 'FG Dispatch'), ('OTHER', 'Other Movement')], db_index=True, help_text='Auto-classified category from movement type and part prefix', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_batch', models.ForeignKey(blank=True, help_text='Batch audit trail for bulk uploads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb51_transactions', to='core.uploadbatch')),
                ('week', models.ForeignKey(blank=True, db_column='week_code', help_text='Mapped week code bucket (e.g. w-2026-08-01)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb51_transactions', to='core.weekdefinition', to_field='week_code')),
            ],
            options={
                'verbose_name': 'MB51 Transaction',
                'verbose_name_plural': 'MB51 Transactions',
                'db_table': 'mb51_transaction',
                'ordering': ['-posting_date', 'material_document'],
                'indexes': [models.Index(fields=['part_number', 'classification', 'week'], name='mb51_transa_part_nu_a1ef47_idx'), models.Index(fields=['posting_date'], name='mb51_transa_posting_ead5b1_idx'), models.Index(fields=['material_document'], name='mb51_transa_materia_1a62ca_idx'), models.Index(fields=['classification'], name='mb51_transa_classif_ebdb70_idx'), models.Index(fields=['week', 'classification'], name='mb51_transa_week_co_b95012_idx')],
            },
        ),
    ]
