# Generated by Django 5.1.9 on 2026-09-25 18:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mb51transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, help_text='Component or FG Part Number (e.g. 7.06496.03.0 or 100201)', max_length=50)),
                ('material_description', models.CharField(blank=True, default='', help_text='Material or Component Description', max_length=255)),
                ('material_type', models.CharField(choices=[('FG', 'Finished Good'), ('RM', 'Raw Material'), ('PM', 'Packaging Material')], db_index=True, help_text="Classification: 'FG' (prefix 7), 'RM' or 'PM'", max_length=10)),
                ('unrestricted_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Unrestricted available inventory on hand', max_digits=12)),
                ('in_quality_insp', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stock currently undergoing quality inspection', max_digits=12)),
                ('blocked', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Blocked / quarantined stock', max_digits=12)),
                ('storage_location', models.CharField(default='SL01', help_text='Storage location (e.g. SL01, RM01, FG01)', max_length=50)),
                ('uom', models.CharField(default='PC', help_text='Unit of Measure (e.g. PC, KG, SET)', max_length=20)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Safety stock buffer threshold', max_digits=12)),
                ('plant', models.CharField(blank=True, default='1001', help_text='Plant code (default 1001)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_batch', models.ForeignKey(blank=True, help_text='Batch audit trail for bulk uploads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reports', to='core.uploadbatch')),
            ],
            options={
                'verbose_name': 'Stock Report',
                'verbose_name_plural': 'Stock Reports',
                'db_table': 'stock_report',
                'ordering': ['part_number', 'storage_location'],
                'indexes': [models.Index(fields=['part_number'], name='stock_repor_part_nu_792285_idx'), models.Index(fields=['part_number', 'storage_location'], name='stock_repor_part_nu_771c05_idx'), models.Index(fields=['material_type'], name='stock_repor_materia_c6214f_idx')],
                'constraints': [models.UniqueConstraint(fields=('part_number', 'storage_location'), name='unique_part_storage_location')],
                'unique_together': {('part_number', 'storage_location')},
            },
        ),
    ]
